/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import '@stencil/router';
import '@stencil/state-tunnel';

import {
  MatchResults,
} from '@stencil/router';

declare global {

  namespace StencilComponents {
    interface AppAboutUs {

    }
  }

  interface HTMLAppAboutUsElement extends StencilComponents.AppAboutUs, HTMLStencilElement {}

  var HTMLAppAboutUsElement: {
    prototype: HTMLAppAboutUsElement;
    new (): HTMLAppAboutUsElement;
  };
  interface HTMLElementTagNameMap {
    'app-about-us': HTMLAppAboutUsElement;
  }
  interface ElementTagNameMap {
    'app-about-us': HTMLAppAboutUsElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-about-us': JSXElements.AppAboutUsAttributes;
    }
  }
  namespace JSXElements {
    export interface AppAboutUsAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppBlogArea {

    }
  }

  interface HTMLAppBlogAreaElement extends StencilComponents.AppBlogArea, HTMLStencilElement {}

  var HTMLAppBlogAreaElement: {
    prototype: HTMLAppBlogAreaElement;
    new (): HTMLAppBlogAreaElement;
  };
  interface HTMLElementTagNameMap {
    'app-blog-area': HTMLAppBlogAreaElement;
  }
  interface ElementTagNameMap {
    'app-blog-area': HTMLAppBlogAreaElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-blog-area': JSXElements.AppBlogAreaAttributes;
    }
  }
  namespace JSXElements {
    export interface AppBlogAreaAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppContactArea {

    }
  }

  interface HTMLAppContactAreaElement extends StencilComponents.AppContactArea, HTMLStencilElement {}

  var HTMLAppContactAreaElement: {
    prototype: HTMLAppContactAreaElement;
    new (): HTMLAppContactAreaElement;
  };
  interface HTMLElementTagNameMap {
    'app-contact-area': HTMLAppContactAreaElement;
  }
  interface ElementTagNameMap {
    'app-contact-area': HTMLAppContactAreaElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-contact-area': JSXElements.AppContactAreaAttributes;
    }
  }
  namespace JSXElements {
    export interface AppContactAreaAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppFaqArea {

    }
  }

  interface HTMLAppFaqAreaElement extends StencilComponents.AppFaqArea, HTMLStencilElement {}

  var HTMLAppFaqAreaElement: {
    prototype: HTMLAppFaqAreaElement;
    new (): HTMLAppFaqAreaElement;
  };
  interface HTMLElementTagNameMap {
    'app-faq-area': HTMLAppFaqAreaElement;
  }
  interface ElementTagNameMap {
    'app-faq-area': HTMLAppFaqAreaElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-faq-area': JSXElements.AppFaqAreaAttributes;
    }
  }
  namespace JSXElements {
    export interface AppFaqAreaAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppFeaturesArea {

    }
  }

  interface HTMLAppFeaturesAreaElement extends StencilComponents.AppFeaturesArea, HTMLStencilElement {}

  var HTMLAppFeaturesAreaElement: {
    prototype: HTMLAppFeaturesAreaElement;
    new (): HTMLAppFeaturesAreaElement;
  };
  interface HTMLElementTagNameMap {
    'app-features-area': HTMLAppFeaturesAreaElement;
  }
  interface ElementTagNameMap {
    'app-features-area': HTMLAppFeaturesAreaElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-features-area': JSXElements.AppFeaturesAreaAttributes;
    }
  }
  namespace JSXElements {
    export interface AppFeaturesAreaAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppFooter {

    }
  }

  interface HTMLAppFooterElement extends StencilComponents.AppFooter, HTMLStencilElement {}

  var HTMLAppFooterElement: {
    prototype: HTMLAppFooterElement;
    new (): HTMLAppFooterElement;
  };
  interface HTMLElementTagNameMap {
    'app-footer': HTMLAppFooterElement;
  }
  interface ElementTagNameMap {
    'app-footer': HTMLAppFooterElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-footer': JSXElements.AppFooterAttributes;
    }
  }
  namespace JSXElements {
    export interface AppFooterAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppHeader {

    }
  }

  interface HTMLAppHeaderElement extends StencilComponents.AppHeader, HTMLStencilElement {}

  var HTMLAppHeaderElement: {
    prototype: HTMLAppHeaderElement;
    new (): HTMLAppHeaderElement;
  };
  interface HTMLElementTagNameMap {
    'app-header': HTMLAppHeaderElement;
  }
  interface ElementTagNameMap {
    'app-header': HTMLAppHeaderElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-header': JSXElements.AppHeaderAttributes;
    }
  }
  namespace JSXElements {
    export interface AppHeaderAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppHome {

    }
  }

  interface HTMLAppHomeElement extends StencilComponents.AppHome, HTMLStencilElement {}

  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
  }
  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-home': JSXElements.AppHomeAttributes;
    }
  }
  namespace JSXElements {
    export interface AppHomeAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppMissionArea {

    }
  }

  interface HTMLAppMissionAreaElement extends StencilComponents.AppMissionArea, HTMLStencilElement {}

  var HTMLAppMissionAreaElement: {
    prototype: HTMLAppMissionAreaElement;
    new (): HTMLAppMissionAreaElement;
  };
  interface HTMLElementTagNameMap {
    'app-mission-area': HTMLAppMissionAreaElement;
  }
  interface ElementTagNameMap {
    'app-mission-area': HTMLAppMissionAreaElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-mission-area': JSXElements.AppMissionAreaAttributes;
    }
  }
  namespace JSXElements {
    export interface AppMissionAreaAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppPreloader {

    }
  }

  interface HTMLAppPreloaderElement extends StencilComponents.AppPreloader, HTMLStencilElement {}

  var HTMLAppPreloaderElement: {
    prototype: HTMLAppPreloaderElement;
    new (): HTMLAppPreloaderElement;
  };
  interface HTMLElementTagNameMap {
    'app-preloader': HTMLAppPreloaderElement;
  }
  interface ElementTagNameMap {
    'app-preloader': HTMLAppPreloaderElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-preloader': JSXElements.AppPreloaderAttributes;
    }
  }
  namespace JSXElements {
    export interface AppPreloaderAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppProfile {
      'match': MatchResults;
    }
  }

  interface HTMLAppProfileElement extends StencilComponents.AppProfile, HTMLStencilElement {}

  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };
  interface HTMLElementTagNameMap {
    'app-profile': HTMLAppProfileElement;
  }
  interface ElementTagNameMap {
    'app-profile': HTMLAppProfileElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-profile': JSXElements.AppProfileAttributes;
    }
  }
  namespace JSXElements {
    export interface AppProfileAttributes extends HTMLAttributes {
      'match'?: MatchResults;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppRoadmapArea {

    }
  }

  interface HTMLAppRoadmapAreaElement extends StencilComponents.AppRoadmapArea, HTMLStencilElement {}

  var HTMLAppRoadmapAreaElement: {
    prototype: HTMLAppRoadmapAreaElement;
    new (): HTMLAppRoadmapAreaElement;
  };
  interface HTMLElementTagNameMap {
    'app-roadmap-area': HTMLAppRoadmapAreaElement;
  }
  interface ElementTagNameMap {
    'app-roadmap-area': HTMLAppRoadmapAreaElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-roadmap-area': JSXElements.AppRoadmapAreaAttributes;
    }
  }
  namespace JSXElements {
    export interface AppRoadmapAreaAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppRoot {

    }
  }

  interface HTMLAppRootElement extends StencilComponents.AppRoot, HTMLStencilElement {}

  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
  }
  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-root': JSXElements.AppRootAttributes;
    }
  }
  namespace JSXElements {
    export interface AppRootAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppServicesArea {

    }
  }

  interface HTMLAppServicesAreaElement extends StencilComponents.AppServicesArea, HTMLStencilElement {}

  var HTMLAppServicesAreaElement: {
    prototype: HTMLAppServicesAreaElement;
    new (): HTMLAppServicesAreaElement;
  };
  interface HTMLElementTagNameMap {
    'app-services-area': HTMLAppServicesAreaElement;
  }
  interface ElementTagNameMap {
    'app-services-area': HTMLAppServicesAreaElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-services-area': JSXElements.AppServicesAreaAttributes;
    }
  }
  namespace JSXElements {
    export interface AppServicesAreaAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppSubscribeArea {

    }
  }

  interface HTMLAppSubscribeAreaElement extends StencilComponents.AppSubscribeArea, HTMLStencilElement {}

  var HTMLAppSubscribeAreaElement: {
    prototype: HTMLAppSubscribeAreaElement;
    new (): HTMLAppSubscribeAreaElement;
  };
  interface HTMLElementTagNameMap {
    'app-subscribe-area': HTMLAppSubscribeAreaElement;
  }
  interface ElementTagNameMap {
    'app-subscribe-area': HTMLAppSubscribeAreaElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-subscribe-area': JSXElements.AppSubscribeAreaAttributes;
    }
  }
  namespace JSXElements {
    export interface AppSubscribeAreaAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppTeamArea {

    }
  }

  interface HTMLAppTeamAreaElement extends StencilComponents.AppTeamArea, HTMLStencilElement {}

  var HTMLAppTeamAreaElement: {
    prototype: HTMLAppTeamAreaElement;
    new (): HTMLAppTeamAreaElement;
  };
  interface HTMLElementTagNameMap {
    'app-team-area': HTMLAppTeamAreaElement;
  }
  interface ElementTagNameMap {
    'app-team-area': HTMLAppTeamAreaElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-team-area': JSXElements.AppTeamAreaAttributes;
    }
  }
  namespace JSXElements {
    export interface AppTeamAreaAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppTokenDistributionArea {

    }
  }

  interface HTMLAppTokenDistributionAreaElement extends StencilComponents.AppTokenDistributionArea, HTMLStencilElement {}

  var HTMLAppTokenDistributionAreaElement: {
    prototype: HTMLAppTokenDistributionAreaElement;
    new (): HTMLAppTokenDistributionAreaElement;
  };
  interface HTMLElementTagNameMap {
    'app-token-distribution-area': HTMLAppTokenDistributionAreaElement;
  }
  interface ElementTagNameMap {
    'app-token-distribution-area': HTMLAppTokenDistributionAreaElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-token-distribution-area': JSXElements.AppTokenDistributionAreaAttributes;
    }
  }
  namespace JSXElements {
    export interface AppTokenDistributionAreaAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppTrustArea {

    }
  }

  interface HTMLAppTrustAreaElement extends StencilComponents.AppTrustArea, HTMLStencilElement {}

  var HTMLAppTrustAreaElement: {
    prototype: HTMLAppTrustAreaElement;
    new (): HTMLAppTrustAreaElement;
  };
  interface HTMLElementTagNameMap {
    'app-trust-area': HTMLAppTrustAreaElement;
  }
  interface ElementTagNameMap {
    'app-trust-area': HTMLAppTrustAreaElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-trust-area': JSXElements.AppTrustAreaAttributes;
    }
  }
  namespace JSXElements {
    export interface AppTrustAreaAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppVerticalSocial {

    }
  }

  interface HTMLAppVerticalSocialElement extends StencilComponents.AppVerticalSocial, HTMLStencilElement {}

  var HTMLAppVerticalSocialElement: {
    prototype: HTMLAppVerticalSocialElement;
    new (): HTMLAppVerticalSocialElement;
  };
  interface HTMLElementTagNameMap {
    'app-vertical-social': HTMLAppVerticalSocialElement;
  }
  interface ElementTagNameMap {
    'app-vertical-social': HTMLAppVerticalSocialElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-vertical-social': JSXElements.AppVerticalSocialAttributes;
    }
  }
  namespace JSXElements {
    export interface AppVerticalSocialAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppVideoArea {

    }
  }

  interface HTMLAppVideoAreaElement extends StencilComponents.AppVideoArea, HTMLStencilElement {}

  var HTMLAppVideoAreaElement: {
    prototype: HTMLAppVideoAreaElement;
    new (): HTMLAppVideoAreaElement;
  };
  interface HTMLElementTagNameMap {
    'app-video-area': HTMLAppVideoAreaElement;
  }
  interface ElementTagNameMap {
    'app-video-area': HTMLAppVideoAreaElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-video-area': JSXElements.AppVideoAreaAttributes;
    }
  }
  namespace JSXElements {
    export interface AppVideoAreaAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppWelcome {

    }
  }

  interface HTMLAppWelcomeElement extends StencilComponents.AppWelcome, HTMLStencilElement {}

  var HTMLAppWelcomeElement: {
    prototype: HTMLAppWelcomeElement;
    new (): HTMLAppWelcomeElement;
  };
  interface HTMLElementTagNameMap {
    'app-welcome': HTMLAppWelcomeElement;
  }
  interface ElementTagNameMap {
    'app-welcome': HTMLAppWelcomeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-welcome': JSXElements.AppWelcomeAttributes;
    }
  }
  namespace JSXElements {
    export interface AppWelcomeAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
